CC = gcc
CFLAGS = -Wall -Wextra -std=c11

TARGET = sistema

OBJ = main.o deposito.o produto.o persistencia.o

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJ)

main.o: main.c deposito.h produto.h persistencia.h struct.h
	$(CC) $(CFLAGS) -c main.c

deposito.o: deposito.c deposito.h struct.h
	$(CC) $(CFLAGS) -c deposito.c

produto.o: produto.c produto.h struct.h
	$(CC) $(CFLAGS) -c produto.c

persistencia.o: persistencia.c persistencia.h struct.h
	$(CC) $(CFLAGS) -c persistencia.c

clean:
	rm -f *.o $(TARGET)

run: $(TARGET)
	./$(TARGET)
